### ISSUE TITLE
Exporting crashes while filtering for agencies

### ISSUE THREAD

**Issue by Josef-A** [afimb/gtfslib-python#49]
Hi,

I try to use the export plugin to filter out all agencies except one and then save it as a GTFS feed.

It crashes since there is no relation defined between agencies and fare_attributes (or fare_rules).

The filter rule is:
--filter="Agency.agency_name=='SL'"

Maybe I have misunderstood how to use the filter parameter. In that case, could you give me an example of how to filter out agencies while exporting. It would be very useful.

The stack trace:
Traceback (most recent call last):
  File "R:/Skript/gtfs_routines/gtfs_lib_run.py", line 15, in <module>
    gtfsplugins.gtfsrun.main()
  File "R:\Skript\gtfslib-python\gtfsplugins\gtfsrun.py", line 101, in main
    retval = plugin.run(context, **kwargs)
  File "R:\Skript\gtfslib-python\gtfsplugins\export.py", line 112, in run
    for fareattr in context.dao().fare_attributes(fltr=context.args.filter, prefetch_fare_rules=False):
  File "R:\Skript\gtfslib-python\gtfslib\dao.py", line 336, in fare_attributes
    query = _AutoJoiner(self._orm, query, fltr).autojoin()
  File "R:\Skript\gtfslib-python\gtfslib\dao.py", line 449, in autojoin
    self._query = self._query.join(clazz)
  File "R:\PythonEnv\gtfs_env\PythonEnv\lib\site-packages\sqlalchemy\orm\query.py", line 1969, in join
    from_joinpoint=from_joinpoint)
  File "<string>", line 2, in _join
  File "R:\PythonEnv\gtfs_env\PythonEnv\lib\site-packages\sqlalchemy\orm\base.py", line 201, in generate
    fn(self, *args[1:], **kw)
  File "R:\PythonEnv\gtfs_env\PythonEnv\lib\site-packages\sqlalchemy\orm\query.py", line 2113, in _join
    outerjoin, full, create_aliases, prop)
  File "R:\PythonEnv\gtfs_env\PythonEnv\lib\site-packages\sqlalchemy\orm\query.py", line 2186, in _join_left_to_right
    self._join_to_left(l_info, left, right, onclause, outerjoin, full)
  File "R:\PythonEnv\gtfs_env\PythonEnv\lib\site-packages\sqlalchemy\orm\query.py", line 2315, in _join_to_left
    "Tried joining to %s, but got: %s" % (right, ae))
sqlalchemy.exc.InvalidRequestError: Could not find a FROM clause to join from.  Tried joining to <class 'gtfslib.model.Agency'>, but got: Can't find any foreign key relationships between 'fare_attributes' and 'agency'.

Since my GTFS feed do not use fares I just commented out the lines in export.py where the fare_attributes and fare_rules. (Line 110 to 122). The it worked.

Regards 
          Josef Andersson

**Comment by laurentg** [comment]
Thanks for the report. I'll have a look at the issue.

**Comment by laurentg** [comment]
There is indeed a bug in the auto-joining mechanism. When filtering fare attributes on anything other than the fare attribute itself, the joins are not properly generated. The complete fix is not trivial to implement (there are corner cases to handle, for example where a fare attribute contains an empty rule, or a rule referencing an filtered route but an unfiltered zone, etc...). I've provided a workaround by simply ignoring the filter for fare attributes and rules during the export.

**Comment by laurentg** [comment]
See #50 for a proper solution to the GTFS export filtering issue.

**Comment by laurentg** [comment]
To be exact, see #51 for a proper solution.
