### ISSUE TITLE
zones are not deleted when a feed is deleted

### ISSUE THREAD

**Issue by elad661** [afimb/gtfslib-python#58]
Causing 

```
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/sqlalchemy/engine/base.py", line 1159, in _execute_context
    context)
  File "/usr/lib64/python3.5/site-packages/sqlalchemy/engine/default.py", line 459, in do_executemany
    cursor.executemany(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: zones.feed_id, zones.zone_id
```
when trying to update a feed.
https://github.com/afimb/gtfslib-python/blob/master/gtfslib/dao.py#L72 simply has no mention of zones.

This should be a one-line fix.

**Comment by laurentg** [comment]
Thanks for reporting. It should be easy to fix indeed.
