### ISSUE TITLE
Can't use gtfslib-python with mysql

### ISSUE THREAD

**Issue by elad661** [afimb/gtfslib-python#62]
I'm building a web app, which means sqlite is not the right choice of database for me (I use it for prototyping, but for production I need an actual DB).

If I try to use gtfsdbloader with mysql (using the mysql+pymsql:// "protocol"), I get the following error:

```
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/sqlalchemy/sql/compiler.py", line 2329, in visit_create_table
    and not first_pk)
  File "/usr/lib64/python3.5/site-packages/sqlalchemy/sql/compiler.py", line 242, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/usr/lib64/python3.5/site-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "/usr/lib64/python3.5/site-packages/sqlalchemy/sql/compiler.py", line 2360, in visit_create_column
    first_pk=first_pk
  File "/usr/lib64/python3.5/site-packages/sqlalchemy/dialects/mysql/base.py", line 966, in get_column_specification
    column.type, type_expression=column)
  File "/usr/lib64/python3.5/site-packages/sqlalchemy/sql/compiler.py", line 290, in process
    return type_._compiler_dispatch(self, **kw)
  File "/usr/lib64/python3.5/site-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "/usr/lib64/python3.5/site-packages/sqlalchemy/sql/compiler.py", line 2770, in visit_string
    return self.visit_VARCHAR(type_, **kw)
  File "/usr/lib64/python3.5/site-packages/sqlalchemy/dialects/mysql/base.py", line 1318, in visit_VARCHAR
    self.dialect.name)
sqlalchemy.exc.CompileError: VARCHAR requires a length on dialect mysql

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/gtfsdbloader", line 9, in <module>
    load_entry_point('gtfslib==0.1.0', 'console_scripts', 'gtfsdbloader')()
  File "/usr/lib/python3.5/site-packages/gtfslib/gtfsdbloader.py", line 71, in main
    dao = Dao(arguments['<database>'], sql_logging=arguments['--logsql'], schema=arguments['--schema'])
  File "/usr/lib/python3.5/site-packages/gtfslib/dao.py", line 52, in __init__
    self._orm = _Orm(engine, schema=schema)
  File "/usr/lib/python3.5/site-packages/gtfslib/orm.py", line 321, in __init__
    self._metadata.create_all(engine)
  File "/usr/lib64/python3.5/site-packages/sqlalchemy/sql/schema.py", line 3848, in create_all
    tables=tables)
  File "/usr/lib64/python3.5/site-packages/sqlalchemy/engine/base.py", line 1920, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/usr/lib64/python3.5/site-packages/sqlalchemy/engine/base.py", line 1529, in _run_visitor
    **kwargs).traverse_single(element)
  File "/usr/lib64/python3.5/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/usr/lib64/python3.5/site-packages/sqlalchemy/sql/ddl.py", line 733, in visit_metadata
    _is_metadata_operation=True)
  File "/usr/lib64/python3.5/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/usr/lib64/python3.5/site-packages/sqlalchemy/sql/ddl.py", line 767, in visit_table
    include_foreign_key_constraints=include_foreign_key_constraints
  File "/usr/lib64/python3.5/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/usr/lib64/python3.5/site-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/lib64/python3.5/site-packages/sqlalchemy/engine/base.py", line 996, in _execute_ddl
    if not self.schema_for_object.is_default else None)
  File "<string>", line 1, in <lambda>
  File "/usr/lib64/python3.5/site-packages/sqlalchemy/sql/elements.py", line 436, in compile
    return self._compiler(dialect, bind=bind, **kw)
  File "/usr/lib64/python3.5/site-packages/sqlalchemy/sql/ddl.py", line 26, in _compiler
    return dialect.ddl_compiler(dialect, self, **kw)
  File "/usr/lib64/python3.5/site-packages/sqlalchemy/sql/compiler.py", line 216, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/usr/lib64/python3.5/site-packages/sqlalchemy/sql/compiler.py", line 242, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/usr/lib64/python3.5/site-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "/usr/lib64/python3.5/site-packages/sqlalchemy/sql/compiler.py", line 2340, in visit_create_table
    (table.description, column.name, ce.args[0])
  File "/usr/lib64/python3.5/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib64/python3.5/site-packages/sqlalchemy/util/compat.py", line 185, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib64/python3.5/site-packages/sqlalchemy/sql/compiler.py", line 2329, in visit_create_table
    and not first_pk)
  File "/usr/lib64/python3.5/site-packages/sqlalchemy/sql/compiler.py", line 242, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/usr/lib64/python3.5/site-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "/usr/lib64/python3.5/site-packages/sqlalchemy/sql/compiler.py", line 2360, in visit_create_column
    first_pk=first_pk
  File "/usr/lib64/python3.5/site-packages/sqlalchemy/dialects/mysql/base.py", line 966, in get_column_specification
    column.type, type_expression=column)
  File "/usr/lib64/python3.5/site-packages/sqlalchemy/sql/compiler.py", line 290, in process
    return type_._compiler_dispatch(self, **kw)
  File "/usr/lib64/python3.5/site-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "/usr/lib64/python3.5/site-packages/sqlalchemy/sql/compiler.py", line 2770, in visit_string
    return self.visit_VARCHAR(type_, **kw)
  File "/usr/lib64/python3.5/site-packages/sqlalchemy/dialects/mysql/base.py", line 1318, in visit_VARCHAR
    self.dialect.name)
sqlalchemy.exc.CompileError: (in table 'feed_info', column 'feed_id'): VARCHAR requires a length on dialect mysql
```

Seems that mysql mandates specifying the length of some fields.

If you don't want to specify the length of those fields, is there a non-sqlite database you do support? PostgreSQL maybe?

**Comment by laurentg** [comment]
Only sqlite and PostgreSQL have been tested. If you can use it, I would suggest you to do so. Also IMHO PostgreSQL is better in many aspect than mysql.

**Comment by elad661** [comment]
PostgreSQL is a bit more difficult to set up and also a bit slower for my specific use-case (from what I'm reading online, at least), so I rather use mysql/mariadb unless there's no other choice.

**Comment by laurentg** [comment]
There was no plan in the initial scope to support database other than PostgreSQL or SQLite, but the added value of SQLAlchemy is to shield against the underlying DB engine. Having said that, I'm a bit worried about adding arbitrary length attribute to fields that do not have known limitations. Is there a way to specify to mysql that strings are unlimited?

**Comment by elad661** [comment]
Unfortunately, no, there's no way to have unlimited strings in mysql. However, I doubt you'll encounter a GTFS feed in which a route_id (for example) is longer than 255 characters, or a feed in which route_desc is longer than 4096 characters.

There exists at least one other GTFS library for python which sets the maximum length on fields, like the example here: https://github.com/OpenTransitTools/gtfsdb/blob/master/gtfsdb/model/stop.py

I do understand why you might not want to add those limits though, I guess I can install PostgreSQL if there's no other choice.

**Comment by laurentg** [comment]
@elad661 OK for adding length, with having relatively large default length (255 for IDs and 4096 for descriptions, I guess we could use the values used in your example project as a baseline). Would you mind proposing a PR with this changes?

**Comment by elad661** [comment]
I'll submit a PR. Would you be okay with using just 191 characters for IDs? apparently mysql has a length limit on primary keys, which means if I want my database to use the utf8mb4 encoding 255 is too long (since 255*4 = 1020 which is above the 767 bytes limit)

see https://stackoverflow.com/questions/1814532/1071-specified-key-was-too-long-max-key-length-is-767-bytes for more information.

**Comment by elad661** [comment]
I've decided to give up on this and just install PostgreSQL instead.
